name: story_viewer
description: This package provides common story view experience for any Flutter app.
version: 0.0.8
homepage: https://github.com/furkansarihan/story_viewer

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  extended_image: ^1.1.1
  flutter_screenutil: ^2.3.1
  flutter_spinkit: ^4.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
